# Generated by Django 4.2.2 on 2023-06-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="word_count",
        ),
    ]
